version: '3.8'

services:

  db:
    image: postgres
    container_name: lushkov_db_servlets
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./createTables.sql:/docker-entrypoint-initdb.d/1-createTables.sql
      - ./insertData.sql:/docker-entrypoint-initdb.d/2-insertData.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
  web:
    build: .
    container_name: lushkov_webapp
    ports:
      - 8080:8080
    environment:
      POSTGRES_URL: db
    links:
      - db
    depends_on:
      db:
        condition: service_healthy