version: '3.1'

services:

  db:
    image: postgres
    container_name: lushkov_db_docker
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
  app:
    image: app
    container_name: lushkov_app_docker
    ports:
      - 8080:8080
    environment:
      POSTGRES_URL: db
    links:
      - db
    depends_on:
      db:
        condition: service_healthy